import Head from "next/head";
import { useState } from "react";
import AppNavbar from "../components/navbar";
import Image from "next/image";
import styled from "styled-components";

const StyledDiv = styled.div`
	display: flex;
	color: white;
	align-items: center;
	justify-content: center;
	flex-direction: column;
	background-color: rgba(0, 0, 0, 0.5);
	border-radius: 10px;
	padding: 10px;
	margin: 10px;
`;

const StyledGrid = styled.div`
	color: white;
	align-items: center;
	justify-content: center;
	display: grid;
	grid-template-columns: 2fr 2fr;
	grid-template-rows: 2fr 2fr;
	grid-gap: 10px;
	padding: 10px;
	margin: 10px;
`;

const StyledGridItem = styled.div`
	color: white;
	align-items: center;
	justify-content: center;
	background-color: rgba(0, 0, 0, 0.5);
	border-radius: 10px;
	padding: 10px;
	margin: 10px;
	border: 2px;
	border-style: solid;
`;

const StyledButton = styled.button`
	display: flex;
	align-items: center;
	justify-content: center;
	flex-direction: column;
	color: white;
	background-color: #1a73e8;
	border: none;
	border-radius: 4px;
	padding: 10px;
	margin: 2px;
`;

export default function Home() {
	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<div
				style={{
					zIndex: -1,
					position: "absolute",
					top: 0,
					left: 0,
					width: "100%",
					height: "100%",
					overflow: "hidden",
				}}>
				<Image
					src='/bg.jpg'
					alt='Background Image'
					layout='fill'
					objectFit='cover'
					quality={100}
				/>
			</div>
			<AppNavbar />
			<StyledDiv>
				<h1>Home</h1>
				<StyledGrid>
					<StyledGridItem>
						<h2>Professions Manager</h2>
					</StyledGridItem>
					<StyledGridItem>
						<h2>Professions Importer</h2>
					</StyledGridItem>
				</StyledGrid>
			</StyledDiv>
		</>
	);
}
